---
groups:
- name: Ops Manager
  jobs:
  - create-opsman-vm
  - create-oms-workspace
  - install-opsmgr-binairies
  - configure-opsmgr
  - start-monitoring-in-oms
  - wipe-env


- name: Servers Pool
  jobs:
  - provision-servers
  - install-automation-agent
  - wipe-mongods-env



resources:
- name: opsmgr-pipeline
  type: git
  source:
    uri: https://github.com/schabiyo/syolab-mongodb-opsmgr.git
    branch: master

jobs:
- name: provision-servers
  plan:
  - get: opsmgr-pipeline
    trigger: false
  - task: provision
    file: opsmgr-pipeline/ci/azure/tasks/mongod/create-mongods.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_GROUP: {{MONGOD_RESOURCE_GROUP}}
      AZURE_RESOURCE_LOCATION: {{MONGOD_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
      NB_NODES: {{NB_NODES}}
      MONGOD_DATA_DISK_TYPE: {{MONGOD_DATA_DISK_TYPE}}
      MONGOD_SERVER_PREFIX: {{MONGOD_SERVER_PREFIX}}
      MONGOD_SSHKEY_PRIVATE: {{MONGOD_SSHKEY_PRIVATE}}
      MONGOD_SSHKEY_PUBLIC: {{MONGOD_SSHKEY_PUBLIC}}

- name: install-automation-agent
  plan:
  - get: opsmgr-pipeline
    trigger: true
    passed: [provision-servers]
  - task: Install Automation agent 
    file: opsmgr-pipeline/ci/azure/tasks/mongod/install-automation-agent.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      OPSMGR_CENTRAL_URL: {{OPSMGR_CENTRAL_URL}}
      AZURE_RESOURCE_GROUP: {{MONGOD_RESOURCE_GROUP}}
      AZURE_RESOURCE_LOCATION: {{MONGOD_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
      NB_NODES: {{NB_NODES}}
      MMS_BASE_URL: {{MMS_BASE_URL}}
      OPSMGR_PROJECT_ID: {{OPSMGR_PROJECT_ID}}
      OPSMGR_API_KEY: {{OPSMGR_API_KEY}}
      MONGOD_SERVER_PREFIX: {{MONGOD_SERVER_PREFIX}}
      MONGOD_SSHKEY_PRIVATE: {{MONGOD_SSHKEY_PRIVATE}}
      MONGOD_SSHKEY_PUBLIC: {{MONGOD_SSHKEY_PUBLIC}}


    
    
- name: create-opsman-vm
  serial_groups: [oms]
  plan:
  - get: opsmgr-pipeline
    trigger: false
  - task: provision
    file: opsmgr-pipeline/ci/azure/tasks/create-opsmgr-vm.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_GROUP: {{AZURE_RESOURCE_GROUP}}
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SSHKEY_PRIVATE: {{OPSMGR_SSHKEY_PRIVATE}}
      OPSMGR_SSHKEY_PUBLIC: {{OPSMGR_SSHKEY_PUBLIC}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
      OPSMGR_DATA_DISK_TYPE: {{OPSMGR_DATA_DISK_TYPE}}
      OPSMGR_DATA_DISK_SIZE: {{OPSMGR_DATA_DISK_SIZE}}
  - task: Format Data Disk as XFS
    file: opsmgr-pipeline/ci/azure/tasks/format-dataXfs.yml
    attempts: 3
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
  - task: Disable Hupe Page
    file: opsmgr-pipeline/ci/azure/tasks/disable-hugepage.yml
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
  - task: Disable NUMA
    file: opsmgr-pipeline/ci/azure/tasks/disable-numa.yml
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}


- name: create-oms-workspace
  serial: true
  public: true
  serial_groups: [oms]
  plan:
    - get:  opsmgr-pipeline
      trigger: true
    - task: create-oms-workspace
      file: opsmgr-pipeline/ci/azure/tasks/oms/create-oms-workspace.yml
      params:
        AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
        AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
        AZURE_SECRET: {{AZURE_SECRET}}
        AZURE_TENANT: {{AZURE_TENANT}}
        AZURE_RESOURCE_LOCATION: {{OMS_WORKSPACE_LOCATION}}
        AZURE_RESOURCE_GROUP: {{AZURE_RESOURCE_GROUP}}
        OMS_WORKSPACE_NAME: {{OMS_WORKSPACE_NAME}}
        OMS_WORKSPACE_SKU: {{OMS_WORKSPACE_SKU}}


- name: start-monitoring-in-oms
  serial: true
  plan:
  - aggregate:
    - get:  opsmgr-pipeline
      passed: [create-oms-workspace,configure-opsmgr]
      trigger: true
  - task: start-monitoring-oms
    file: opsmgr-pipeline/ci/azure/tasks/oms/create-oms-workspace.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      AZURE_RESOURCE_GROUP: {{AZURE_RESOURCE_GROUP}}
      OMS_WORKSPACE_NAME: {{OMS_WORKSPACE_NAME}}
      OMS_WORKSPACE_SKU: {{OMS_WORKSPACE_SKU}}


- name: install-opsmgr-binairies
  serial_groups: [oms]
  plan:
  - get: opsmgr-pipeline
    trigger: true
    passed: [create-opsman-vm]
  - task: Get Binaries
    file: opsmgr-pipeline/ci/azure/tasks/config-opsmgr-prereqs.yml
    params:
      OPSMGR_SSHKEY_PRIVATE: {{OPSMGR_SSHKEY_PRIVATE}}
      OPSMGR_SSHKEY_PUBLIC: {{OPSMGR_SSHKEY_PUBLIC}}
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
  - task: Install Application and Backup Databases
    file: opsmgr-pipeline/ci/azure/tasks/install-opsmgr-mongods.yml 
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}

  - task: Install Ops Manager
    file: opsmgr-pipeline/ci/azure/tasks/install-opsmgr.yml 
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}

- name: configure-opsmgr
  plan:
  - get: opsmgr-pipeline
    trigger: true
    passed: [install-opsmgr-binairies]
  - task: configure-opsmgr
    file: opsmgr-pipeline/ci/azure/tasks/configure-opsmgr.yml
    attempts: 10
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      OPSMGR_REGISTRATION_USERNAME: {{OPSMGR_REGISTRATION_USERNAME}}
      OPSMGR_REGISTRATION_PASSWORD: {{OPSMGR_REGISTRATION_PASSWORD}}
      OPSMGR_REGISTRATION_FIRSTNAME: {{OPSMGR_REGISTRATION_FIRSTNAME}}
      OPSMGR_REGISTRATION_LASTNAME: {{OPSMGR_REGISTRATION_LASTNAME}}
      OPSMGR_CONFIG_EMAIL_FROM: {{OPSMGR_CONFIG_EMAIL_FROM}}
      OPSMGR_CONFIG_EMAIL_REPLYTO: {{OPSMGR_CONFIG_EMAIL_REPLYTO}}
      OPSMGR_CONFIG_EMAIL_ADMIN: {{OPSMGR_CONFIG_EMAIL_ADMIN}}
      OPSMGR_CONFIG_EMAIL_TRANSPORT: {{OPSMGR_CONFIG_EMAIL_TRANSPORT}}
      OPSMGR_CONFIG_EMAIL_HOSTNAME: {{OPSMGR_CONFIG_EMAIL_HOSTNAME}}
      OPSMGR_CONFIG_EMAIL_PORT: {{OPSMGR_CONFIG_EMAIL_PORT}}
      OPSMGR_CENTRAL_URL: {{OPSMGR_CENTRAL_URL}}
      OPSMGR_SSHKEY_PRIVATE: {{OPSMGR_SSHKEY_PUBLIC}}
      OPSMGR_SSHKEY_PRIVATE: {{OPSMGR_SSHKEY_PRIVATE}}
      OPSMGR_PEM: {{OPSMGR_PEM}}
      OPSMGR_PEM_PWD: {{OPSMGR_PEM}}
      OPSMGR_CLIENT_CERTIFICATE_MODE: {{OPSMGR_PEM}}


- name: wipe-mongods-env
  plan:
  - aggregate:
    - get: opsmgr-pipeline
  - task: Destroy all MongoD nodes
    file: opsmgr-pipeline/ci/azure/tasks/mongod/wipe-mongods-env.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_GROUP: {{MONGOD_RESOURCE_GROUP}}


- name: wipe-env
  plan:
  - aggregate:
    - get: opsmgr-pipeline
  - task: wipe
    file: opsmgr-pipeline/ci/azure/tasks/wipe-env.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_GROUP: {{AZURE_RESOURCE_GROUP}}

