---
resources:
- name: opsmgr-pipeline
  type: git
  source:
    uri: https://github.com/schabiyo/syolab-mongodb-opsmgr.git
    branch: master

jobs:
- name: create-opsman-vm
  plan:
  - get: opsmgr-pipeline
    trigger: true
  - task: provision
    file: opsmgr-pipeline/ci/azure/tasks/create-opsmgr-vm.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_GROUP: {{AZURE_RESOURCE_GROUP}}
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SSHKEY_PRIVATE: {{OPSMGR_SSHKEY_PRIVATE}}
      OPSMGR_SSHKEY_PUBLIC: {{OPSMGR_SSHKEY_PUBLIC}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
      OPSMGR_DATA_DISK_TYPE: {{OPSMGR_DATA_DISK_TYPE}}
      OPSMGR_DATA_DISK_SIZE: {{OPSMGR_DATA_DISK_SIZE}}
  - task: Format Data Disk as XFS
    file: opsmgr-pipeline/ci/azure/tasks/format-dataXfs.yml
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
  - task: Disable Hupe Page
    file: opsmgr-pipeline/ci/azure/tasks/disable-hugepage.yml
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
  - task: Disable NUMA
    file: opsmgr-pipeline/ci/azure/tasks/disable-numa.yml
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}

- name: install-opsmgr-binairies
  plan:
  - get: opsmgr-pipeline
    trigger: true
    passed: [create-opsman-vm]
  - task: Get Binaries
    file: opsmgr-pipeline/ci/azure/tasks/config-opsmgr-prereqs.yml
    params:
      OPSMGR_SSHKEY_PRIVATE: {{OPSMGR_SSHKEY_PRIVATE}}
      OPSMGR_SSHKEY_PUBLIC: {{OPSMGR_SSHKEY_PUBLIC}}
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}
  - task: Install Application and Backup Databases
    file: opsmgr-pipeline/ci/azure/tasks/install-opsmgr-mongods.yml 
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}

  - task: Install Ops Manager
    file: opsmgr-pipeline/ci/azure/tasks/install-opsmgr.yml 
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      AZURE_SERVER_ADMIN: {{AZURE_SERVER_ADMIN}}

- name: configure-opsmgr
  plan:
  - get: opsmgr-pipeline
    trigger: true
    passed: [install-opsmgr-binairies]
  - task: configure-opsmgr
    file: opsmgr-pipeline/ci/azure/tasks/configure-opsmgr.yml
    params:
      AZURE_RESOURCE_LOCATION: {{AZURE_RESOURCE_LOCATION}}
      OPSMGR_SERVER_HOSTNAME: {{OPSMGR_SERVER_HOSTNAME}}
      OPSMGR_REGISTRATION_USERNAME: {{OPSMGR_REGISTRATION_USERNAME}}
      OPSMGR_REGISTRATION_PASSWORD: {{OPSMGR_REGISTRATION_PASSWORD}}
      OPSMGR_REGISTRATION_FIRSTNAME: {{OPSMGR_REGISTRATION_FIRSTNAME}}
      OPSMGR_REGISTRATION_LASTNAME: {{OPSMGR_REGISTRATION_LASTNAME}}
      OPSMGR_CONFIG_EMAIL_FROM: {{OPSMGR_CONFIG_EMAIL_FROM}}
      OPSMGR_CONFIG_EMAIL_REPLYTO: {{OPSMGR_CONFIG_EMAIL_REPLYTO}}
      OPSMGR_CONFIG_EMAIL_ADMIN: {{OPSMGR_CONFIG_EMAIL_ADMIN}}
      OPSMGR_CONFIG_EMAIL_TRANSPORT: {{OPSMGR_CONFIG_EMAIL_TRANSPORT}}
      OPSMGR_CONFIG_EMAIL_HOSTNAME: {{OPSMGR_CONFIG_EMAIL_HOSTNAME}}
      OPSMGR_CONFIG_EMAIL_PORT: {{OPSMGR_CONFIG_EMAIL_PORT}}


- name: wipe-env
  plan:
  - aggregate:
    - get: opsmgr-pipeline
  - task: wipe
    file: opsmgr-pipeline/ci/azure/tasks/wipe-env.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{AZURE_SUBSCRIPTION_ID}}
      AZURE_CLIENT_ID: {{AZURE_CLIENT_ID}}
      AZURE_SECRET: {{AZURE_SECRET}}
      AZURE_TENANT: {{AZURE_TENANT}}
      AZURE_RESOURCE_GROUP: {{AZURE_RESOURCE_GROUP}}

