---
- hosts: opsManager
  remote_user: AZURE_SERVER_ADMIN
  become: yes
  #  tasks:
  #- name: get automation apikey
  #   shell: mongo 127.0.0.1:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne().k)"
  #  register: opsmanager_apikey
  #- debug: var=opsmanager_apikey
  #- name: get automation groupid
  #  shell: mongo 127.0.0.1:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne()._id.str)" 
  #  register: opsmanager_groupid
  #- debug: var=opsmanager_groupid
- hosts: mongoDs
  remote_user: AZURE_SERVER_ADMIN
  become: yes
  vars:
    autoagent: mongodb-mms-automation-agent-manager-latest.x86_64.rhel7.rpm
    opsmgr_groupid: OPSMGR_PROJECT_ID
    opsmgr_apikey: OPSMGR_API_KEY
    mmsBaseUrl: MMS_BASE_URL
  tasks:
  - name: Adjust hostname
    hostname:
      name: "{{inventory_hostname}}"    
  - name: download automation agent via http
    get_url: url="MMS_BASE_URL/download/agent/automation/{{autoagent}}" dest="/home/AZURE_SERVER_ADMIN/{{autoagent}}"
  - name: install automation agent
    yum: name=/home/AZURE_SERVER_ADMIN/{{autoagent}} state=present
  - name: update config mmsGroupId
    shell: sed -i -e "s/mmsGroupId.*/mmsGroupId={{opsmgr_groupid}}/" /etc/mongodb-mms/automation-agent.config
  - name: update config mmsApiKey
    shell: sed -i -e "s/mmsApiKey.*/mmsApiKey={{opsmgr_apikey}}/" /etc/mongodb-mms/automation-agent.config
  - name: update config mmsBaseUrl to http, if no ssl
    lineinfile:
      path: /etc/mongodb-mms/automation-agent.config
      regexp: '^mmsBaseUrl='
      line: 'mmsBaseUrl=MMS_BASE_URL'
  - name: setup data directory
    file: path=/data state=directory mode=0755 owner=mongod group=mongod
  - name: start agent
    service: name=mongodb-mms-automation-agent state=restarted
