---
- hosts: OpsManager
  remote_user: AZURE_SERVER_ADMIN
  tasks:
  - name: disable hugepage support
    shell: /bin/echo never | /usr/bin/sudo /usr/bin/tee /sys/kernel/mm/transparent_hugepage/enabled 
  - name: disable hugepage defrag
    shell: /bin/echo never | /usr/bin/sudo /usr/bin/tee /sys/kernel/mm/transparent_hugepage/defrag
