---
- hosts: OpsManager
  remote_user: AZURE_SERVER_ADMIN
  become: yes
  tasks:
  - yum: name=xfsprogs state=present
  - shell: mkfs.xfs /dev/sdc # for Azure, migth be different with pther cloud providers 
  - mount: name=/data src=/dev/sdc fstype=xfs opts=defaults,noatime state=mounted
