---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: schabiyo/mongodb-azure-ci 
    tag: latest


params:
  AZURE_RESOURCE_LOCATION:
  AZURE_SERVER_ADMIN:
  OPSMGR_SERVER_HOSTNAME:
  


inputs:
    - name: opsmgr-pipeline
    - name: keys-out

run:
    path: opsmgr-pipeline/ci/azure/tasks/install-opsmgr-mongods.sh
